name: Lint Code Base

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  mega-linter:
    name: MegaLinter
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Run MegaLinter
      uses: nvuillam/mega-linter@v4
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
